project:
  type: website
  output-dir: docs

website:
  title: DS Club
  navbar:
    left:
      - href: index.qmd
        text: О клубе
      - projects.qmd # Мои проекты
      - teams.qmd # Команды
      - portfolios.qmd # Портфолио
      
format:
  html:
    theme: lux
    css: styles.css
    toc: true



