---
pagetitle: "DS Club"
page-layout: custom
section-divs: false
toc: false
css: index.css
---

::: {.hero-banner}

::: {.content-block}

::: {.hero-text}

# Добро пожаловать в DS Club

### Клуб неравнодушных к моделькам, циферкам и графикам

- Поддержка базы знаний по анализу данных и ML
- Организация сетевых мероприятий для студентов
- Лекции и семинары по теории и практике анализа данных
- Проведение исследовательских проектов на реальных датасетах.
- Организация мастер-классов по использованию инструментов анализа данных.

:::
:::
:::

::: {.content-block}
::: {.features}

::: {.feature}
### Команды
Среди нас социологи, филологи, математики и психологи. Мы разные но объединены любовью к анализу данных. Давайте знакомиться!

::: {.learn-more}
[Узнать больше »](teams.qmd)
:::
:::

::: {.feature}
### Проекты
Мы занимаемся различными проектами, используя современные методы и инструменты, включая машинное обучение и статистический анализ.

::: {.learn-more}
[Узнать больше »](projects.qmd)
:::
:::

::: {.feature}
### Расписание
Мы встречаемся 3 раза в месяц как в оффлайн, так и в онлайн формате. В перерыве от R и Python едим печеньки и пьем кофе.  

::: {.learn-more}
[Узнать больше »](calendar.qmd)
:::
:::


:::
:::